### ISSUE TITLE
Error: Could not find dependent Exec[concat_/etc/named/pri/example.com.conf] 

### ISSUE THREAD

**Issue by panaceya** [camptocamp/puppet-bind#33]
Error: Could not find dependent Exec[concat_/etc/named/pri/example.com.conf] for File[/var/lib/puppet/concat/_etc_named_pri_example.com.conf/fragments/10_example.com.A.example.com] at /etc/puppet/modules/concat/manifests/fragment.pp:123

site.pp
```
...
class bind {
    include bind::base
}

...		 
		Exec {
			path => '/bin:/sbin:/usr/sbin:/usr/bin',
		}
 
...

node "x"{
       ...
		include bind

		bind::key { 'key_dyn.example.com':
			ensure => present,
			secret => 'x'
		}
		     
		bind::zone {'example.com':
			zone_contact => 'contact.example.com',
			zone_ns      => 'ns0.example.com',
			zone_serial  => '1',
			zone_ttl     => '300',
			zone_origin  => 'example.com',
			is_dynamic   => true,
			allow_update => ['key_dyn.example.com']
		}
		
		bind::a { 'example.com':
			ensure    => present,
			zone      => 'example.com',
			ptr       => false,
			hash_data => {
				'host1' => { owner => '192.168.0.1', },
				'host2' => { owner => '192.168.0.2', },
			},
		}
}



```

Puppet v3.6.2, CentOS 7

**Comment by cjeanneret** [comment]
Precision before closing:
you cannot add records to a dynamic zone, as it will break bind mechanism:
* dynamic records are to be set with some ```nsupdate``` command, and it creates a .jnl file
* the jnl file is then synced to the flat, standard file "when bind have the time to do so".
* if bind detects new records in the standard file, it won't be able to restart nor reload the zone, because the jnl file is considered as inconsistent. 

It would be possible to do what you intend to do (dynamic zone while having records in puppet) iff puppet uses nsupdate command instead of flat file "edition" (well, override with a template). For now, this isn't planed.
